# Generated by Django 3.1.2 on 2020-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeSpeciesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_input', models.DateTimeField(auto_now_add=True)),
                ('local_name', models.CharField(max_length=250, verbose_name='Local Name')),
                ('scientific_name', models.CharField(max_length=250, null=True)),
                ('category', models.CharField(max_length=250, null=True)),
                ('origin', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(blank=True)),
                ('nursery', models.CharField(max_length=250)),
                ('remark', models.CharField(max_length=250)),
            ],
        ),
    ]
