# Generated by Django 3.1.2 on 2020-10-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treespeciesdata',
            name='tree_species_img',
            field=models.ImageField(blank=True, null=True, upload_to='tree_species_img/', verbose_name='Tree Species'),
        ),
    ]
