# Generated by Django 3.1 on 2020-11-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_treespeciesdata_tree_species_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treespeciesdata',
            name='remark',
        ),
        migrations.AddField(
            model_name='treespeciesdata',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='treespeciesdata',
            name='remarks',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='treespeciesdata',
            name='nursery',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
