# Generated by Django 3.1.2 on 2020-11-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20201107_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treespeciesdata',
            name='tree_species_img',
            field=models.ImageField(blank=True, null=True, upload_to='tree_species_img/', verbose_name='Tree Species Image'),
        ),
    ]
