# Generated by Django 3.1.2 on 2020-11-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20201116_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantingRecord',
        ),
    ]
