# Generated by Django 3.1 on 2020-09-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, verbose_name='Blog Author')),
                ('title', models.CharField(max_length=200, verbose_name='Blog Title')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
