# Generated by Django 3.1.2 on 2020-10-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201020_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='caption_first_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='caption_main_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='caption_second_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='first_body_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='main_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='second_body_img',
        ),
    ]
