# Generated by Django 3.1.2 on 2020-10-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201021_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/', verbose_name='Thumbnail'),
        ),
    ]
