# Generated by Django 3.1.2 on 2020-11-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_planted', models.CharField(max_length=250)),
                ('programme_name', models.CharField(max_length=250)),
                ('programme_img', models.ImageField(blank=True, null=True, upload_to='programme_img/', verbose_name='Programme Image')),
                ('location', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
                ('area', models.FloatField()),
                ('species', models.CharField(max_length=255)),
                ('participants', models.CharField(max_length=250)),
            ],
        ),
    ]
