# Generated by Django 3.1.2 on 2020-11-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingrecord',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
