# Generated by Django 3.1.2 on 2020-11-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0003_auto_20201118_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created_cart', models.DateTimeField(auto_now_add=True)),
                ('cart_local_name', models.CharField(max_length=250)),
                ('cart_scientific_name', models.CharField(max_length=250)),
                ('cart_species_img', models.ImageField(blank=True, null=True, upload_to='cart_species_img/', verbose_name='Species Image')),
                ('cart_species_category', models.CharField(max_length=250)),
                ('cart_species_quantity', models.IntegerField(null=True, verbose_name='Quantity')),
            ],
        ),
    ]
