# Generated by Django 3.1.2 on 2020-11-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0004_cartspecies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartspecies',
            name='cart_species_quantity',
        ),
        migrations.AddField(
            model_name='cartspecies',
            name='cart_species_descriptions',
            field=models.TextField(blank=True, null=True, verbose_name='Descriptions'),
        ),
        migrations.AddField(
            model_name='cartspecies',
            name='cart_species_total',
            field=models.IntegerField(null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='cartspecies',
            name='cart_local_name',
            field=models.CharField(max_length=250, verbose_name='Local Name'),
        ),
        migrations.AlterField(
            model_name='cartspecies',
            name='cart_scientific_name',
            field=models.CharField(max_length=250, verbose_name='Scientific Name'),
        ),
        migrations.AlterField(
            model_name='cartspecies',
            name='cart_species_category',
            field=models.CharField(max_length=250, verbose_name='Category'),
        ),
    ]
